### PR TITLE
Add the Master Class Habits to the Week list as well as combining intro and the first question

### PR DESCRIPTION
**Pull request by e2thex**

### CODE REVIEW

**Comment by crittermike** [comment]
I think I disagree on combining intro and first question into the same session. I liked having the first session be introductions for the people to get to know each other (we filled out and talked through [this slide deck](https://docs.google.com/presentation/d/1aW1mfZeMnCvi6hUkyr1syHoo7HVd0kbz0Zvd_So-krM/edit#slide=id.g120d7c85a14_0_475)) and talk about "what even is coaching?" and ponder that a bit before getting into any specific questions. 

That said, I don't feel super strongly about it and I can see benefits to getting the first question in on the first session so you have something to review on the 2nd session.

**Comment by e2thex** [comment]
Ohh I thought you had combined those (that's why I did it). So is the first master class in week one or two?

my we do the first master class: Ask one question at a time and that can be the first habit 

It is in the intro section

**Comment by e2thex** [comment]
I separated it out.

**Comment by crittermike** [comment]
We did first master class + intro in week 1.

**Review by crittermike — APPROVED** [review]

**Pull request merged**
